version: '3'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16  # 定义子网范围

services:
  server:
    build:
      context: .
      # 指定dockerfile启动容器
      dockerfile: ./Dockerfile
    container_name: go-yinhuadm.cc
    restart: always
    ports:
      - "10001:8080"
    volumes:
      - ${SERVER_DIR}/configs/config.yml:/app/configs/config.yml
    networks:
      my_network:
        ipv4_address: 172.28.1.3  # 设置容器的 IPv4 地址